### ISSUE TITLE
When I use the HPO my jupyter notebook kernel dies

### ISSUE THREAD

**Issue by lorenzofamiglini** [automl/SMAC3#581] opened 2019-12-22 14:39 UTC
```
conf_space = ConfigurationSpace()

one_layer = UniformIntegerHyperparameter("h1", 130, 210)
#second_layer = UniformIntegerHyperparameter("h2", 1, 5)
momentum = UniformFloatHyperparameter("momentum", 0.1, 0.9, default_value = 0.9)
learning_r = UniformFloatHyperparameter("learning_rate_init", 0.001, 0.1)

conf_space.add_hyperparameters([one_layer, momentum,learning_r])
random_f_init = conf_space.sample_configuration(10)

def get_error_nn(param):
    adactive_seed = int(param['momentum']*param['learning_rate_init']*5000)
    mlp = MLPClassifier(hidden_layer_sizes = (param["h1"],),momentum = param["momentum"],
                        learning_rate_init=param["learning_rate_init"],
                        random_state = adactive_seed)
    strat = StratifiedKFold(n_splits = 9, random_state = seme_fisso)
    scores = cross_val_score(mlp, X_train, y_train, cv = strat, scoring = 'accuracy')
    return 1 - np.mean(scores)

scen = Scenario({"run_obj": "quality","runcount-limit": 109,
                 "cs": conf_space,"deterministic": "true"
                     })

smac_rf_lcb = SMAC4HPO(scenario = scen,tae_runner = get_error_nn,initial_design = None,
               initial_design_kwargs = {'max_config_fracs': 10/109},
               initial_configurations = random_f_init,acquisition_function = LCB,
               )
incumbent3 = smac_rf_lcb.optimize()
inc_value_LCB = get_error_nn(incumbent3)

print("Optimized Value: %.2f" % (1-inc_value_LCB))
```

### 
I don't know the reason why with HBO my code works, but with HPO nothing

**Comment by mfeurer** [comment] 2020-01-03 13:13
Thanks a lot for reporting this. Could you please run this piece of code within ipython and provide us with the error message or, if it crashes due to a segfault, increase the log level (by adding `logging.basicConfig(level=logging.DEBUG)` to the script) and post the output?

**Comment by lorenzofamiglini** [comment] 2020-01-08 21:17
172.21.13.45 - Microsoft\JohnDoe [08/Apr/2001:17:39:04 -0800] "GET /scripts/iisadmin/ism.dll?http/serv HTTP/1.0" 200 3401
127.0.0.1 - frank [10/Oct/2000:13:55:36 -0700] "GET /apache_pb.gif HTTP/1.0" 200 2326
 
this should be the output from the logging file

**Comment by orenmatar** [comment] 2020-01-21 13:36
I'm having the same problem... basically just trying to run a simple example:

from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.model_selection import cross_val_score
import numpy as np
from sklearn.datasets import load_breast_cancer
from smac.facade.func_facade import fmin_smac
dataset = load_breast_cancer()
X = dataset['data']
y = dataset['target']

def logistic_from_cnf(C):
    lr = LogisticRegression(C=C)
    scores = cross_val_score(lr, X, y, cv=4)
    return 1-np.mean(scores)

x, cost, _ = fmin_smac(func=logistic_from_cnf,  # function
                       x0=[0.1],    # default configuration
                       bounds=[(0.1, 3)],  # limits
                       maxfun=100)  


getting no error message... the kernal just dies... I tried to use examples from documentation and this package doesn't seem to work at all...

**Comment by orenmatar** [comment] 2020-01-21 13:39
also when I just copied the example:

```
def branin(x):
    x1 = x[0]
    x2 = x[1]
    a = 1.
    b = 5.1 / (4.*np.pi**2)
    c = 5. / np.pi
    r = 6.
    s = 10.
    t = 1. / (8.*np.pi)
    ret = a*(x2-b*x1**2+c*x1-r)**2+s*(1-t)*np.cos(x1)+s
    return ret

x, cost, _ = fmin_smac(func=branin,  # function
                       x0=[0, 0],    # default configuration
                       bounds=[(-5, 10), (0, 15)],  # limits
                       maxfun=10,   # maximum number of evaluations
                       rng=3)  
```

the kernel dies... does anyone know how to get this package to work?

**Comment by pvk-developer** [comment] 2020-05-21 17:18
If you run it using `python` you will get a `Segmentation fault (core dumped)`. I'm not able to find a solution to this problem / issue. However, I have run this code on another machine and it works fine. I belive that has to do somenthing with the OS that you are running.

**Comment by mfeurer** [comment] 2021-06-25 15:49
This should be fixed since quite some time due to an update of the pyrfr. If it is still an issue, please check https://automl.github.io/auto-sklearn/development/faq.html#auto-sklearn-crashes-with-a-segmentation-fault and potentially re-open.

**Closed by mfeurer** 2021-06-25 15:49 UTC
