### ISSUE TITLE
Multiple runs with exactly the same parameter value with deterministic=false

### ISSUE THREAD

**Issue by LavoriniV** [automl/SMAC3#440] opened 2018-05-16 14:08 UTC
Hello,

code for replicating:

        cs = ConfigurationSpace()
        n_sigma_par=UniformFloatHyperparameter("sigma", 1.9,3, default_value=2.0)
        cs.add_hyperparameters([n_sigma_par])

        scenario = Scenario({"run_obj": "quality",   # we optimize quality (alternatively runtime)
                             "runcount-limit": 4,  # maximum function evaluations
                             "cs": cs,               # configuration space
                             "cutoff_time": None,
                             "deterministic": "false"
                             })

        def optimizeIt(cfg):
            start=time.time()
            cfg = {k : float(cfg[k]) for k in cfg if cfg[k]}  

            print (cfg)
            return cfg['sigma']
        smac = SMAC(scenario=scenario, rng=np.random.RandomState(41),
                tae_runner=optimizeIt)

        incumbent = smac.optimize()

and the output that I get is:

    {'sigma': 2.0}
    {'sigma': 2.0}
    {'sigma': 2.076317256617163}
    {'sigma': 2.0}

Is this an expected behavior?

**Comment by mlindauer** [comment] 2018-05-16 15:00
Hi,

Since you specified the target function as non-deterministic (`deterministic : "false"`), yes that's expected behavior.
Even if you would set `deterministic : "true"`, SMAC will still be non-determinstic because of its default behavior of using the same time for function evaluations and acquisition function optimization. 
We changed the latter behavior for deterministic target functions in the development branch---hopefully soon merged into the master branch.

Best,
Marius

**Closed by mlindauer** 2018-05-16 15:00 UTC

**Comment by mlindauer** [comment] 2018-05-16 15:06
sorry, maybe I misunderstood your question....
Please note that `deterministic : "false"` does not relates to SMAC but to the target function. 
See also https://automl.github.io/SMAC3/dev/faq.html
`What is the meaning of deterministic?`
