### ISSUE TITLE
Question about memory usage for MO+MF

### ISSUE THREAD

**Issue by sudoRicheek** [automl/SMAC3#1029] opened 2023-06-03 16:14 UTC
#### Description

I was trying to black-box optimize model parameters under a multi-objective setting:

```
    scenario = Scenario(
        model_search.configspace,
        name=args.run_name,
        output_directory=args.output_dir,
        objectives=model_search.get_objectives,
        walltime_limit=args.wall_time_limit,  # After n seconds, we stop the hyperparameter optimization
        n_trials=args.n_trials,  # Evaluate max n different trials
        min_budget=args.min_budget,  # Train the model using a architecture configuration for at least n epochs
        max_budget=args.max_budget,  # Train the model using a architecture configuration for at most n epochs
        seed=args.seed,
        n_workers=torch.cuda.device_count(),
    )

    # We want to run n random configurations before starting the optimization.
    initial_design = MFFacade.get_initial_design(scenario, n_configs=args.initial_n_configs)
    intensifier = Hyperband(scenario, eta=args.successive_halving_eta,
                            incumbent_selection="highest_budget") # SuccessiveHalving can be used
    multi_objective_algorithm = ParEGO(scenario)

    smac = MFFacade(
        scenario,
        model_search.train,
        initial_design=initial_design,
        multi_objective_algorithm=multi_objective_algorithm,
        intensifier=intensifier,
        overwrite=False,
    )

    incumbents = smac.optimize()
```

When I run this setting for `n_trials=200`, the memory usage keeps on slowly increasing as the optimization progresses. The memory usage resets when I stop the run and continue from the saved logs. Is the increasing memory usage the intended behaviour? Is there any way to circumvent the problem?

#### Versions

2.0.1

**Comment by eddiebergman** [comment] 2023-06-06 10:57
Hi @sudoRicheek,

It's unlikely to intended behaviour but very could easily happen with anything that gets saved as a reference. Do you have any idea where this memory usage is coming from. I'm not familiar with debugging these kinds of memory issues but could be worth investigating.

Best,
Eddie

**Comment by sudoRicheek** [comment] 2023-06-06 11:19
Hi @eddiebergman 

Unfortunately not :( I have no clue what the issue might be. The memory usage starts around 4GB and keeps increasing (even up to 14-15GB) as the optimization progresses. Eventually, it runs out of memory and raises "Oserror: [errno 12] cannot allocate memory". Note that the GPU memory usage stays constant.

Please let me know if I can be of more help.

**Comment by alexandertornede** [comment] 2023-07-25 12:23
Since there is no further reaction, we close this issue for now. Feel free to re-open.

**Closed by alexandertornede** 2023-07-25 12:23 UTC
