### ISSUE TITLE
Error when using "rf_with_instances.py"

### ISSUE THREAD

**Issue by ffalfred** [automl/SMAC3#298] opened 2017-08-03 09:16 UTC
Hello,

I am pretty new with this program, but someone recommended to me and it seems pretty interesting.
However, when trying to run any example (like branin or rosenbrock), it appears the same issue (in the file from the repository or the one in the python/site-packages):

File "/home/rpt539/.local/lib/python3.4/site-packages/smac/epm/rf_with_instances.py", line 124, in _train
    self.rf.fit(data, rng=self.rng)
TypeError: fit() got an unexpected keyword argument 'rng'

I have tried changing the file in that line, to:
  self.rf.fit(data, self.rng)
And it seems it works (at least, no more error appears); however, I do not know if the program is working well or I have touched something that should not be touched.

Thanks!

**Comment by mlindauer** [comment] 2017-08-03 09:21
Thanks for reporting this issue.

Unfortunately, I cannot reproduce this issue on my machine. Which version of the pyrfr package do you use? 
If you use the master branch of pyrfr (and not the recommended 0.4.0 on pypi), you encounter some issues because the pyrfr API has slightly changed. This will be fixed in the next SMAC release.

btw: your fix should be fine.

**Comment by ffalfred** [comment] 2017-08-03 09:32
Thanks for the quick answer.

The version of pyrfr package is actually 0.4.0 .

**Comment by sfalkner** [comment] 2017-08-03 09:35
Beware, if you update pyrfr, you will have to use the development branch of SMAC.

**Closed** 2017-11-29 09:04 UTC
