### ISSUE TITLE
resumable optimization

### ISSUE THREAD

**Issue by zkurtz** [automl/SMAC3#321] opened 2017-10-03 14:07 UTC
It would be useful to me to be able to run SMAC for say 30 minutes, consider the results, and then run it again for another 30 minutes, building on the previous results without starting over. If this is already a feature, a demo would be useful, as I've not been able to figure it out. This thread shows analogous functionality in hyperopt:  https://github.com/hyperopt/hyperopt/issues/267

**Comment by AndreBiedenkapp** [comment] 2017-10-04 08:00
This is being worked on in pull request #263 and a duplicate of issue #193.

**Comment by mlindauer** [comment] 2017-10-04 08:41
Dear Zach,

Thank your for proposing this feature.
As Andre pointed out, we have implemented this feature and it is part of the development branch of SMAC now. So, it will be part of the next SMAC release.
(Please check the documentation for an example)

However, I wonder whether this is really the feature you are looking for. 
SMAC already provides the current best configuration (so-called incumbent) at every point in time (both in `stdout` and in `smac3-output*/traj_aclib2.json`) and also shows you some statistics (e.g., the estimated cost of the incumbent). If you are interested in more information, we would be interested to learn more about it.

Best,
Marius

**Comment by zkurtz** [comment] 2017-10-04 12:57
Marius, thank you for the prompt response!  I'll take a look at what is getting pushed.  The feature I'm looking for is not simply awareness of the performance of the current smac run.  After considering the results of a smac run, I want to be able to start a new run with different hyper-hyperparameters (i.e. smac parameters, not the hyperparameters that smac is optimizing over), but I want the new run to build on all previous evaluations rather than starting from scratch.  Maybe the PR you reference above enables this.  I'll take a look.

**Comment by zkurtz** [comment] 2017-10-18 15:23
A python demo of the new functionality resulting from pull request #263 would be useful.

**Comment by shukon** [comment] 2017-10-18 22:11
@zkurtz Hi! I added an example of how to restore from within the python code in #326.
However, this feature is not really intended for changing other SMAC-parameters than *output_dir*, *wallclock_limit*, *runcount_limit* or *tuner-timeout*. Depending on what you intend to change, it might or might not break something. I can give you a more detailed answer, if you decide to share the parameters you want to adapt. However, using this option does continue the SMAC-run with the new specified scenario (not the scenario in the folder to be restored from, but the one passed via the `--scenario SCEN_PATH` commandline argument), so you might be able to use it. It's just not tested (or intended) for any other than the above mentioned parameters.
To use it via the cmd-line, change into the directory from where you previously executed SMAC and try
`python (..)/scripts/smac --scenario NEW_SCEN_PATH --restore_state SMAC_OUTPUT_FOLDER`.
Is this what you are looking for?

**Closed** 2018-04-26 14:11 UTC
Labels: duplicate
