### ISSUE TITLE
First run crashed, abort. Please check your setup

### ISSUE THREAD

**Issue by jiahuanluo** [automl/SMAC3#502] opened 2019-03-11 03:43 UTC
When I repaced SVC by [ThunderSVM](https://github.com/Xtra-Computing/thundersvm) on GPUs in ```examples/svm.py```, I got errors shown below:
 
```INFO:smac.utils.io.cmd_reader.CMDReader:Output to smac3-output_2019-03-11_03:38:01_310603
Default Value: 0.56
Optimizing! Depending on your machine, this might take a few minutes.
INFO:smac.facade.smac_facade.SMAC:Optimizing a deterministic scenario for quality without a tuner timeout - will make SMAC deterministic!
INFO:smac.stats.stats.Stats:##########################################################
INFO:smac.stats.stats.Stats:Statistics:
INFO:smac.stats.stats.Stats:#Incumbent changed: -1
INFO:smac.stats.stats.Stats:#Target algorithm runs: 1 / 1.0
INFO:smac.stats.stats.Stats:#Configurations: 1
INFO:smac.stats.stats.Stats:Used wallclock time: 0.71 / inf sec 
INFO:smac.stats.stats.Stats:Used target algorithm runtime: 0.71 / inf secINFO:smac.stats.stats.Stats:##########################################################
INFO:smac.facade.smac_facade.SMAC:Final Incumbent: None
Traceback (most recent call last):
  File "smac_test.py", line 123, in <module>
    incumbent = smac.optimize()
  File "/usr/local/lib/python3.5/dist-packages/smac-0.10.0-py3.5.egg/smac/facade/smac_facade.py", line 489, in optimize
    incumbent = self.solver.run()
  File "/usr/local/lib/python3.5/dist-packages/smac-0.10.0-py3.5.egg/smac/optimizer/smbo.py", line 188, in run
    self.start()
  File "/usr/local/lib/python3.5/dist-packages/smac-0.10.0-py3.5.egg/smac/optimizer/smbo.py", line 159, in start
    self.incumbent = self.initial_design.run()
  File "/usr/local/lib/python3.5/dist-packages/smac-0.10.0-py3.5.egg/smac/initial_design/single_config_initial_design.py", line 90, in run
    raise err
  File "/usr/local/lib/python3.5/dist-packages/smac-0.10.0-py3.5.egg/smac/initial_design/single_config_initial_design.py", line 87, in run
    "0"))
  File "/usr/local/lib/python3.5/dist-packages/smac-0.10.0-py3.5.egg/smac/tae/execute_ta_run.py", line 225, in start
    raise FirstRunCrashedException("First run crashed, abort. "
smac.tae.execute_ta_run.FirstRunCrashedException: First run crashed, abort. Please check your setup -- we assume that your defaultconfiguration does not crashes. (To deactivate this exception, use the SMAC scenario option 'abort_on_first_run_crash')
```

I think it may be because SMAC runs in parallel and ThunderSVM also runs in parallel. The two level parallelism seems to cause the issue. Is there a way to set SMAC to run in serial instead of in parallel?

Thanks.

**Comment by mlindauer** [comment] 2019-03-11 08:13
Hi,

If you don't activate the parallel mode explicitly, SMAC is serial.

It looks like there is some problem in evaluating the default configuration as the first configuration SMAC looks at. To further look into this, we would need a small example such that we can reproduce this error.

Best regards,
Marius

**Comment by jiahuanluo** [comment] 2019-03-11 08:49
Appreciate for your reply.

To reproduce this error, 
1. Install SMAC and build the thunderSVM follow the instructions in [ThunderSVM](https://github.com/Xtra-Computing/thundersvm).
2. Modify examples/svm.py:
2.1 `from thundersvm.python import thundersvmScikit` (according to your path)
2.2 replace line 52 with `clf = thundersvmScikit.SVC(**cfg)`
2.3 replace `poly` with `polynomial`

[svm.zip](https://github.com/automl/SMAC3/files/2951344/svm.zip)
It should reproduce this error.

Thanks.

**Comment by mlindauer** [comment] 2019-03-12 08:21
Sorry, because of an upcoming conference deadline, we don't have the manpower to look into that right now. I hope we will do it at the end of the week or latest early next week.

Cheers,
Marius

**Comment by mlindauer** [comment] 2019-03-15 16:06
Dear Locke,

We looked further into the problem. Since Thundersvm makes use of cuda and GPUs, we are aware of that the `pynisher` can be problematic. 

Could you please try to run the following modified code:
```
smac = SMAC(scenario=scenario, rng=np.random.RandomState(42),
        tae_runner=svm_from_cfg)

smac.solver.intensifier.tae_runner.use_pynisher = False

incumbent = smac.optimize()
```
Please note that SMAC will not enforce a time limit or memory limit by deactivating the pynisher.

Sorry, I have no systems available that meets the installation requirements of ThunderSVM and thus, I cannot test it myself.

Cheers,
Marius

**Comment by jiahuanluo** [comment] 2019-03-16 04:23
Dear Marius,

It works when I deactivated the pynisher.
Thank you!

It seems that there's a bug in smac==0.8.0.
When I run `examples/svm.py`, the error is shown below:

 `TypeError: validate() got an unexpected keyword argument 'output'`

I solve this by reinstall smac with version 0.10.0. 
But the default `pip3 install smac` will install smac==0.8.0.

Thanks again.
Locke

**Comment by mlindauer** [comment] 2019-03-17 09:50
> But the default pip3 install smac will install smac==0.8.0

That should be your local pip cache.
If you use `--no-cache`, pip should always download the newest version.

Since the issue is solved, I will close it.

Cheers,
Marius

**Closed by mlindauer** 2019-03-17 09:50 UTC

**Comment by jiahuanluo** [comment] 2019-03-17 14:26
Yes, but I install SMAC in a newly established docker container.
BTW, how can I set SMAC **not** to save output file or **core** file

Thanks,
Locke

**Comment by poojitharamachandra** [comment] 2019-04-26 21:12
hi Marius,

i am getting the same error  :
FirstRunCrashedException: First run crashed, abort. Please check your setup -- we assume that your defaultconfiguration does not crashes. (To deactivate this exception, use the SMAC scenario option 'abort_on_first_run_crash')

even after adding smac.solver.intensifier.tae_runner.use_pynisher = False

code is at https://github.com/poojitharamachandra/HPO/blob/master/hpo.py

any hints?

**Comment by jiahuanluo** [comment] 2019-04-27 09:37
I found that. It comes from autosklearn, which needs smac==0.8.0.
