### ISSUE TITLE
SMAC deep copying the benchmark

### ISSUE THREAD

**Issue by aaronkl** [automl/SMAC3#432] opened 2018-04-30 11:38 UTC
I want to use SMAC to optimize my benchmark which internally maintains a data structure that is updated every time the benchmark is evaluated. However, it seems that SMAC does a deepcopy of the benchmark object which causes that no internal updates are save.

The following example reproduces the problem:
``

    import numpy as np
    import ConfigSpace
    from smac.facade.smac_facade import SMAC
    from smac.scenario.scenario import Scenario

    class Benchmark(object):

        def __init__(self):
            self.counter = 0

        def objective_function(self, config,**kwargs):
            self.counter += 1
            return np.random.rand()

        def get_configuration_space():
            cs = ConfigSpace.ConfigurationSpace()

            cs.add_hyperparameter(
            ConfigSpace.OrdinalHyperparameter("a", [16, 32, 64, 128, 256, 512], default_value=64))
            return cs

    def objective_function(config, **kwargs):
        y = b.objective_function(config)
        print(b.counter)
        return y

    b = Benchmark()

    cs = b.get_configuration_space()

    scenario = Scenario({"run_obj": "quality",
                     "runcount-limit": 5,
                     "cs": cs,
                     "deterministic": "true",
                     "initial_incumbent": "RANDOM",
                     "output_dir": ""})

    smac = SMAC(scenario=scenario, tae_runner=objective_function)
smac.optimize()
``

**Comment by KEggensperger** [comment] 2018-04-30 11:42
We already figured out that this happens because the pynisher is active (which is not necessary in this case).

@mlindauer Is there already a way to set the argument `use_pynisher` [here](https://github.com/automl/SMAC3/blob/master/smac/tae/execute_func.py#L34)

**Comment by aaronkl** [comment] 2018-04-30 11:46
Setting the use_pynisher FLAG to false, causes the following error:

  File "git/nas_benchmark/comparison/run_smac.py", line 49, in <module>
    smac.optimize()
  File "/home/kleinaa/virtualenv/local/lib/python3.5/site-packages/smac-0.8.0-py3.5.egg/smac/facade/smac_facade.py", line 448, in optimize
    incumbent = self.solver.run()
  File "/home/kleinaa/virtualenv/local/lib/python3.5/site-packages/smac-0.8.0-py3.5.egg/smac/optimizer/smbo.py", line 172, in run
    self.start()
  File "/home/kleinaa/virtualenv/local/lib/python3.5/site-packages/smac-0.8.0-py3.5.egg/smac/optimizer/smbo.py", line 145, in start
    self.incumbent = self.initial_design.run()
  File "/home/kleinaa/virtualenv/local/lib/python3.5/site-packages/smac-0.8.0-py3.5.egg/smac/initial_design/single_config_initial_design.py", line 86, in run
    "0"))
  File "/home/kleinaa/virtualenv/local/lib/python3.5/site-packages/smac-0.8.0-py3.5.egg/smac/tae/execute_ta_run.py", line 176, in start
    self.run_obj == 'quality' and not np.isfinite(cost)):
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**Comment by mlindauer** [comment] 2018-04-30 11:53
Hi Aaron,

running your example without the pynisher gives you the expected result:

```
import numpy as np
import ConfigSpace
from smac.facade.smac_facade import SMAC
from smac.scenario.scenario import Scenario
from smac.tae.execute_func import ExecuteTAFuncDict

class Benchmark(object):

    def __init__(self):
        self.counter = 0

    def objective_function(self, config,**kwargs):
        self.counter += 1
        return np.random.rand()

    def get_configuration_space(self):
        cs = ConfigSpace.ConfigurationSpace()

        cs.add_hyperparameter(
        ConfigSpace.OrdinalHyperparameter("a", [16, 32, 64, 128, 256, 512], default_value=64))
        return cs

def objective_function(config, **kwargs):
    y = b.objective_function(config)
    print(b.counter)
    return y


b = Benchmark()

cs = b.get_configuration_space()


tae = ExecuteTAFuncDict(objective_function,use_pynisher=False)

scenario = Scenario({"run_obj": "quality",
                 "runcount-limit": 5,
                 "cs": cs,
                 "deterministic": "true",
                 "initial_incumbent": "RANDOM",
                 "output_dir": ""})

smac = SMAC(scenario=scenario, tae_runner=tae)
smac.optimize()
```

Output:
```
1
2
3
4
5
```

Sorry, but I cannot reproduce your error.

**Comment by aaronkl** [comment] 2018-04-30 11:59
Do you use the development or master branch?

**Comment by mlindauer** [comment] 2018-04-30 12:01
I tried it with both.

**Comment by aaronkl** [comment] 2018-04-30 12:09
the problem was that I now have to return a scalar value instead of a dict, which I did in my original benchmark

**Comment by mlindauer** [comment] 2018-04-30 12:13
Ok, great that you found it.
So, can we close the issue?

**Closed** 2018-04-30 12:13 UTC
Labels: bug
