### ISSUE TITLE
Algorithm configuration memory issue

### ISSUE THREAD

**Issue by MarieNyst** [automl/SMAC3#895] opened 2022-12-19 16:25 UTC
Hi,

The current version of SMAC can not run algorithm configuration scenarios that where working with version 0.10. In particular, it seems that from version 0.11 there are memory problems: some scenarios crash after about 20 minutes because they reach dozens of Gb of memory (could be linked to [issue 187]( https://github.com/automl/ConfigSpace/issues/187) ).

You can find a zip file with a few log files and the details of the scenarios on which SMAC was run to obtain them [here](https://drive.google.com/file/d/1kC2n_ZCgpy8Cdrwx9PdGRRzRKrnoFxGl/view?usp=sharing)

Note that:
I am running SMAC from command line;
The results I am sending you where all run from the same conda environment so they use the same version of the libraries;
For the logs that end with "CANCELLED" it is simply that I stopped them after a bit more than 24 hours, logs of seed 5 and 6 are in debug mode.

A high level look at the log file:
- the memory problem seems to appear from version 0.11 (see logs of scenario sparrowtoriss on circuitfuzz)
- I have had memory problems with SMAC3-v.1.4 on scenarios using Sparrowtoriss, Clasp, Lingeling, but no problem with cplex and kissat (pcs file in the archive)
- the number of steps of the local search seems to go from more than 10 for each LS in v0.10 to about 2 in v0.11, which could mean that the local search is not much better than random search from then. (see debug output of kissat on circuitfuzz)
However, it might also be that the debug output is giving numbers that are not meaningful. When looking at the code we found that the time per acquisition function "vectorized" is an average over non comparable values.
- the reported "Average configurations per intensify" goes from ~14 in v0.10 to ~30 in v0.11 and then drops to 0 from v1.0

**Comment by mlindauer** [comment] 2022-12-19 16:30
Hi Marie,

Thank you very much for reporting this. 

> When looking at the code we found that the time per acquisition function "vectorized" is an average over non comparable values.

Could you please provide more details on that? Do you have any line number for us?

Best,
Marius

**Comment by jeroenrook** [comment] 2022-12-20 08:56
Hi all, 
I can answer that question. Before local search was vectorized, each individual local search reported (`v0.10,0:optimizer/ei_optimization.py:l310`) the time it took to get the acquisition function value for one configuration. After vectorizing the local search, that value isn't [reported](https://github.com/automl/SMAC3/blob/dd249cdb90c2614d23de7fab6553f3f04edfa60b/smac/acquisition/maximizer/local_search.py#L363) anymore. Instead it reports the average time it takes to compute the acquisition function values over each search iteration. However, the number of iterations is not written to the log. This makes it not possible to (indirectly) compute the time it took on average for getting the acquisition function value for one configuration. 

This could be easily fixed by changing the logging output to report by replacing `np.mean(times)` with `np.sum(times)/np.sum(neighbors_looked_at)`.

**Comment by olegzaikin** [comment] 2022-12-20 09:50
I can confirm this issue. I am trying to parameterize kissat SAT solver by SMAC of version 1.4. In the ROAR mode everything works fine, yet in the SMAC4AC mode smac takes up all 128 Gb RAM just in 1-2 minutes.
A minimal reproducible example:
1. Download 5 files from here
https://disk.yandex.ru/d/zGuASFBvQj9_0w
2. In the same directory, build kissat: 
```
wget https://github.com/arminbiere/kissat/archive/refs/tags/rel-3.0.0.zip
unzip rel-3.0.0.zip
cd kissat-rel-3.0.0/
./configure && make
cp ./kissat-rel-3.0.0/build/kissat ./
```
3. Run 
```
smac --scenario ./scenario --mode SMAC4AC
```
Could you please help with the issue?

**Comment by mlindauer** [comment] 2022-12-20 09:57
Hi Oleg,

Thank you for reporting this. This is in fact a very important observation because it indicates that the problem is not the configspace (as I assumed so far) but part of SMAC.

**Comment by MarieNyst** [comment] 2022-12-20 10:05
Note that I am not using the same pcs file for Kissat and I do not run into problems with it. So the observation from issue 187 about it being linked to log scaled integer might be a good place to look at

**Comment by olegzaikin** [comment] 2022-12-20 10:26
> Note that I am not using the same pcs file for Kissat and I do not run into problems with it. So the observation from issue 187 about it being linked to log scaled integer might be a good place to look at : none of my integers are on log scale for Kissat

You are right! I have just tried to get rid of all log scale in my pcs-file by replacing ']il' with ']i' and now SMAC4AC works. At least it does not take up all the memory anymore. So this is the reason. However, in my case this is crucial to use the log scale. Dear developers, could you please fix this bug?

**Comment by dengdifan** [comment] 2023-01-19 10:49
@olegzaikin Does the memory leak issue still exist with the ConfigSpace version 0.6.1: https://github.com/automl/ConfigSpace/releases/tag/v0.6.1 ? Unfortunately, I cannot test that on my computer, as the first run always crashes.

**Comment by alexandertornede** [comment] 2023-03-30 09:09
@olegzaikin Could you check this again? See the comment of @dengdifan above, please.

**Comment by alexandertornede** [comment] 2023-04-17 09:49
Since there is no more answer from @olegzaikin and the issue does not seem to happen in SMAC 2.0, we close this for now. We do not plan to fix this in v1.4

**Closed by alexandertornede** 2023-04-17 09:49 UTC
Labels: bug

**Comment by olegzaikin** [comment] 2023-05-04 09:24
> @olegzaikin Does the memory leak issue still exist with the ConfigSpace version 0.6.1: https://github.com/automl/ConfigSpace/releases/tag/v0.6.1 ? Unfortunately, I cannot test that on my computer, as the first run always crashes.

Could you please give me a hint how a new ConfigSpace should be used in SMAC 1.4?

**Comment by olegzaikin** [comment] 2024-07-24 07:13
> @olegzaikin Could you check this again? See the comment of @dengdifan above, please.

I've just checked SMAC 1.4 with ConfigSpace 0.7.1 and this combination works on the aforementioned example without any memory leaks. Thank you!

**Comment by benjamc** [comment] 2024-07-24 13:33
Awesome!
